version: "3"

dotenv: [".env"]
silent: true

tasks:
  # Run the main (dashboard) app in DEV mode
  dashboard:
    cmds:
      - cd apps/dashboard && bun run dev
  # Run the server app in DEV mode
  server:
    cmds:
      - cd apps/server && bun run start:dev
  # Deploy the server app in PROD mode with Mau
  deploy-server:
    cmds:
      - cd apps/server && mau deploy
  # Deploy the contract program to the blockchain and update code integrity
  deploy-contract:
    cmds:
      - cd apps/smart-contract && ./build.sh
